language: node_js

node_js:
  - "node"
  - "8"

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm test -- --coverage

after_success:
  - npm install codecov
  - ./node_modules/.bin/codecov -f coverage/lcov.info

notifications:
  email:
    on_success: change
    on_failure: always
